/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BInputCho: typeof import('./src/components/base/BInputCho.vue')['default']
    BInputNumFormat: typeof import('./src/components/base/BInputNumFormat.vue')['default']
    BottomBar: typeof import('./src/components/layout/BottomBar.vue')['default']
    BTab: typeof import('./src/components/base/BTab.vue')['default']
    BValidator: typeof import('./src/components/base/BValidator.vue')['default']
    BVueDatePicker: typeof import('./src/components/base/BVueDatePicker.vue')['default']
    MenuTab: typeof import('./src/components/MenuTab.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    StoreTab: typeof import('./src/components/StoreTab.vue')['default']
    TabEditor: typeof import('./src/components/TabEditor.vue')['default']
    UnitEditPop: typeof import('./src/components/UnitEditPop.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VDataTable: typeof import('vuetify/components')['VDataTable']
    VDivider: typeof import('vuetify/components')['VDivider']
    VPagination: typeof import('vuetify/components')['VPagination']
    VSelect: typeof import('vuetify/components')['VSelect']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
